version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_dwh
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data/processed:/data
    restart: unless-stopped
