version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ecommerce_postgres
    environment:
      POSTGRES_DB: ecommerce_dwh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # ← Снаружи 5433, внутри контейнера 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: